name: DevSecops
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  SCA:
    needs: build # This job depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup rule
        run: echo 'hello rule'
      - name: run SCA scan
        run: echo 'hello sca'

  SAST:
    needs: SCA # This job depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup rule
        run: echo 'hello rule'
      - name: run SAST scan
        run: echo 'hello sast'
  
  DAST:
    needs: SAST # This job depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup rule
        run: echo 'hello rule'
      - name: run SAST scan
        run: echo 'hello sast'

  Container-Scan:
    needs: DAST # This job depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup rule
        run: echo 'hello rule'
      - name: run SAST scan
        run: echo 'hello sast'